/**
 * Typed ABI re-exports for the web bundle.
 *
 * JSON imports give Next.js tree-shaking and keep bundle size predictable.
 * JSON modules aren't narrowed with `as const`, so viem's `Abi` type needs
 * a cast — safe because the ABIs are generated by Hardhat from the Solidity
 * sources and checked in.
 */

import type { Abi } from "viem";

import AssertionRegistry from "@verdict/shared/abi/AssertionRegistry.json";
import VerdictEnforcer from "@verdict/shared/abi/VerdictEnforcer.json";
import EscalationManager from "@verdict/shared/abi/EscalationManager.json";
import ReputationRegistry from "@verdict/shared/abi/ReputationRegistry.json";
import Escrow from "@verdict/shared/abi/Escrow.json";
import ParametricInsurance from "@verdict/shared/abi/ParametricInsurance.json";
import MilestoneVault from "@verdict/shared/abi/MilestoneVault.json";
import AuthenticityCertifier from "@verdict/shared/abi/AuthenticityCertifier.json";

export const abis = {
  assertionRegistry: AssertionRegistry as unknown as Abi,
  verdictEnforcer: VerdictEnforcer as unknown as Abi,
  escalationManager: EscalationManager as unknown as Abi,
  reputationRegistry: ReputationRegistry as unknown as Abi,
  escrow: Escrow as unknown as Abi,
  parametricInsurance: ParametricInsurance as unknown as Abi,
  milestoneVault: MilestoneVault as unknown as Abi,
  authenticityCertifier: AuthenticityCertifier as unknown as Abi,
} as const;

export type AbiKey = keyof typeof abis;
